In [2]:
import requests
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [18]:
r = requests.get('https://collectionapi.metmuseum.org/public/collection/v1/search?q=sunflowers') #2 задание
res = r.json()
sunflower_ids = res.get('objectIDs', [])

In [19]:
sunflower_ids

[436524,
 484935,
 437112,
 210191,
 431264,
 397949,
 656530,
 480725,
 486590,
 485308,
 375281,
 705155,
 11922,
 816522,
 343052,
 20141,
 347980,
 208554,
 403496,
 360837,
 207869,
 437115,
 400581,
 423400,
 707887,
 223828,
 682927,
 57922,
 79739,
 193938,
 649813,
 339347,
 437329,
 208218,
 202228,
 437984,
 761604,
 696949,
 704667,
 822589,
 822590,
 436580,
 436252,
 363282,
 207753,
 437526,
 822570,
 487043,
 203893,
 367434,
 190739,
 2032,
 423237,
 262423,
 839296,
 367817,
 13644,
 18362,
 820022,
 648617,
 761731,
 814626,
 892559,
 207967,
 626832,
 2019,
 701016,
 262430,
 262428,
 841928,
 262378,
 707697,
 205386,
 436535,
 426804,
 633526,
 369073,
 747779,
 436529,
 436121,
 436144,
 852414,
 427872,
 895564,
 436530,
 436534,
 724844,
 437980,
 631808,
 396836,
 834765,
 834580,
 834585]

In [21]:
r_test = requests.get(f'https://collectionapi.metmuseum.org/public/collection/v1/objects/437980')
obj_test = r_test.json() #3 задание

In [22]:
obj_test

{'objectID': 437980,
 'isHighlight': False,
 'accessionNumber': '49.30',
 'accessionYear': '1949',
 'isPublicDomain': True,
 'primaryImage': 'https://images.metmuseum.org/CRDImages/ep/original/DP130999.jpg',
 'primaryImageSmall': 'https://images.metmuseum.org/CRDImages/ep/web-large/DP130999.jpg',
 'additionalImages': [],
 'constituents': [{'constituentID': 161947,
   'role': 'Artist',
   'name': 'Vincent van Gogh',
   'constituentULAN_URL': 'http://vocab.getty.edu/page/ulan/500115588',
   'constituentWikidata_URL': 'https://www.wikidata.org/wiki/Q5582',
   'gender': ''}],
 'department': 'European Paintings',
 'objectName': 'Painting',
 'title': 'Cypresses',
 'culture': '',
 'period': '',
 'dynasty': '',
 'reign': '',
 'portfolio': '',
 'artistRole': 'Artist',
 'artistPrefix': '',
 'artistDisplayName': 'Vincent van Gogh',
 'artistDisplayBio': 'Dutch, Zundert 1853–1890 Auvers-sur-Oise',
 'artistSuffix': '',
 'artistAlphaSort': 'Gogh, Vincent van',
 'artistNationality': 'Dutch',
 'artistBeginDate': '1853',
 'artistEndDate': '1890',
 'artistGender': '',
 'artistWikidata_URL': 'https://www.wikidata.org/wiki/Q5582',
 'artistULAN_URL': 'http://vocab.getty.edu/page/ulan/500115588',
 'objectDate': '1889',
 'objectBeginDate': 1889,
 'objectEndDate': 1889,
 'medium': 'Oil on canvas',
 'dimensions': '36 3/4 x 29 1/8 in. (93.4 x 74 cm)',
 'measurements': [{'elementName': 'Overall',
   'elementDescription': None,
   'elementMeasurements': {'Height': 93.4, 'Width': 74}},
  {'elementName': 'Frame',
   'elementDescription': None,
   'elementMeasurements': {'Depth': 10.795,
    'Height': 116.2052,
    'Width': 96.5202}},
  {'elementName': 'Other',
   'elementDescription': 'glass',
   'elementMeasurements': {'Height': 94.29769, 'Width': 76.517654}}],
 'creditLine': 'Rogers Fund, 1949',
 'geographyType': '',
 'city': '',
 'state': '',
 'county': '',
 'country': '',
 'region': '',
 'subregion': '',
 'locale': '',
 'locus': '',
 'excavation': '',
 'river': '',
 'classification': 'Paintings',
 'rightsAndReproduction': '',
 'linkResource': '',
 'metadataDate': '2023-10-18T04:55:33.33Z',
 'repository': 'Metropolitan Museum of Art, New York, NY',
 'objectURL': 'https://www.metmuseum.org/art/collection/search/437980',
 'tags': [{'term': 'Landscapes',
   'AAT_URL': 'http://vocab.getty.edu/page/aat/300132294',
   'Wikidata_URL': 'https://www.wikidata.org/wiki/Q191163'},
  {'term': 'Cypresses',
   'AAT_URL': 'http://vocab.getty.edu/page/aat/300343641',
   'Wikidata_URL': 'https://www.wikidata.org/wiki/Q146911'}],
 'objectWikidata_URL': 'https://www.wikidata.org/wiki/Q867510',
 'isTimelineWork': True,
 'GalleryNumber': '825'}

In [23]:
#4 задание

# Список для хранения данных каждого объекта
objects_data = []

# Цикл для запроса данных по каждому ID
for object_id in sunflower_ids:
    object_url = f'https://collectionapi.metmuseum.org/public/collection/v1/objects/{object_id}'
    response = requests.get(object_url)
    data = response.json()

    # Сбор необходимой информации
    object_info = {
        "objectID": data.get("objectID"),
        "title": data.get("title"),
        "artistDisplayName": data.get("artistDisplayName"),
        "department": data.get("department"),
        "objectBeginDate": data.get("objectBeginDate"),
        "objectEndDate": data.get("objectEndDate"),
        "period": data.get("period"),
        "objectName": data.get("objectName"),
        "culture": data.get("culture")
    }

    objects_data.append(object_info)

# Создание датафрейма
df = pd.DataFrame(objects_data)

# Подсчёт объектов японской культуры
japanese_culture_count = df[df['culture'] == "Japan"].shape[0]

print(f"Количество объектов японской культуры: {japanese_culture_count}")

Количество объектов японской культуры: 1

In [30]:
df

,objectID,title,artistDisplayName,department,objectBeginDate,objectEndDate,period,objectName,culture
0,436524.0,Sunflowers,Vincent van Gogh,European Paintings,1887.0,1887.0,,Painting,
1,484935.0,Sunflowers,Edward McKnight Kauffer,Modern and Contemporary Art,1921.0,1921.0,,Painting,
2,437112.0,Bouquet of Sunflowers,Claude Monet,European Paintings,1881.0,1881.0,,Painting,
3,210191.0,Vase with sunflowers,Rozenburg Plateelfabriek,European Sculpture and Decorative Arts,1896.0,1896.0,,Vase,
4,431264.0,Sunflowers,Lily Converse,Drawings and Prints,1941.0,1941.0,,Print,
...,...,...,...,...,...,...,...,...,...
88,NaN,None,None,None,NaN,NaN,None,None,None
89,396836.0,The Aesthetic Craze,Currier & Ives,Drawings and Prints,1882.0,1882.0,,Print,
90,834765.0,"A Child's Garden, from ""Picture Poesies""",Arthur Boyd Houghton,Drawings and Prints,1865.0,1874.0,,Print,
91,834580.0,"A Life in a Year–The Garden–Noon, from ""Pictur...",Arthur Boyd Houghton,Drawings and Prints,1866.0,1874.0,,Print,
92,834585.0,"A Life in a Year–The Garden–Noon, from ""Pictur...",Arthur Boyd Houghton,Drawings and Prints,1866.0,1874.0,,Print,

In [33]:
#5 задание
# Запрос к API для получения списка ID
response = requests.get('https://collectionapi.metmuseum.org/public/collection/v1/search?departmentId=6&q=cat')
data = response.json()
cat_ids = data.get('objectIDs', [])[:1000]  # Получение первых 1000 ID

# Сбор данных о каждом объекте
objects_data = []
for object_id in cat_ids:
    object_url = f'https://collectionapi.metmuseum.org/public/collection/v1/objects/{object_id}'
    response = requests.get(object_url)
    data = response.json()

    object_info = {
        "objectID": data.get("objectID"),
        "title": data.get("title"),
        "artistDisplayName": data.get("artistDisplayName"),
        "department": data.get("department"),
        "objectBeginDate": data.get("objectBeginDate"),
        "objectEndDate": data.get("objectEndDate"),
        "period": data.get("period"),
        "objectName": data.get("objectName"),
        "culture": data.get("culture")
    }

    objects_data.append(object_info)

# Создание датафрейма
df = pd.DataFrame(objects_data)

# Анализ данных
most_common_period = df['period'].value_counts().idxmax()

In [34]:
most_common_period

'Edo period (1615–1868)'